# Generated by Django 5.1.5 on 2025-02-03 16:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                default="https://res.cloudinary.com/dsvh54olg/image/upload/v1738599272/profilepic_rzpziq.jpg",
                max_length=255,
                null=True,
                verbose_name="profilepictures/",
            ),
        ),
    ]
