# Generated by Django 5.1.5 on 2025-02-03 15:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_question_solution_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="solution_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
