# Generated by Django 5.1.5 on 2025-01-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.CharField(default='Quantitative Aptitude', max_length=255),
        ),
    ]
