# Generated by Django 5.1.5 on 2025-02-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_category_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution_image',
            field=models.ImageField(default='profilepic.jpg', upload_to='solutions'),
        ),
    ]
