# Generated by Django 5.1.5 on 2025-02-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('B', 'bronze'), ('S', 'silver'), ('G', 'gold'), ('P', 'platinum'), ('D', 'daimond'), ('H', 'heroic'), ('M', 'grand Master')], max_length=1),
        ),
    ]
