# Generated by Django 5.1.5 on 2025-02-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('B', 'bronze'), ('S', 'silver'), ('G', 'gold'), ('P', 'platinum'), ('D', 'daimond'), ('H', 'heroic'), ('M', 'grand Master')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(default=100000),
        ),
    ]
